a=10
b=3.14
c="Hello"
d=True
e=[10,20,30]
f=(10,20,30)
g={"Apple","Banana","mango"}
h={"Name":"John","Age":20}
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))